### PR TITLE
Close  #508: Split db on `application-state` db and `effects` db

### LINKED ISSUE #508: Do not store effects in state
Currently we store effects history in the state. This is wrong. We should store this in dedicated database because it is not affects blockchan. An exception is events. They shuld be stored in state because it significant to business .

### PR DESCRIPTION
**Pull request by Chicker**

### CODE REVIEW

File: node/src/main/scala/pravda/node/servers/ApiRoute.scala [hunk 1]
```diff
@@ -75,12 +76,13 @@ class ApiRoute(abciClient: AbciClient, db: DB, abci: Abci)(implicit executionCon
...
 
-  val balances: Entry[Address, NativeCoin] = balanceEntry(db)
-  val eventsByAddress = eventsByAddressEntry(db)
-  val events = eventsEntry(db)
-  val txIdIndex = txIdIndexEntry(db)
-  val transferEffectsByAddress = transferEffectsEntry(db)
-  val transactionsByAddress = transactionsEntry(db)
+  val balances: Entry[Address, NativeCoin] = balanceEntry(applicationStateDb)
+  val events = eventsEntry(applicationStateDb)
+  val txIdIndex = txIdIndexEntry(applicationStateDb)
```
Comment (fomkin) [inline node/src/main/scala/pravda/node/servers/ApiRoute.scala]: Are you sure that transaction index should be stored in application state?

Comment (Chicker) [reply node/src/main/scala/pravda/node/servers/ApiRoute.scala]: You are right. Is not necessary to store txIdIndex in applicationStateDb
I will change it
