### PR TITLE
Close #199: Stack traces with source references, more teskit abilities 

### LINKED ISSUE #199: Implement stack trace error reporting

### PR DESCRIPTION
**Pull request by vovapolu**
PR also changes `codegen` behavior a little bit. It removes names of args from `method signature` meta, because it's not very convenient to store them without tuples as primitives in vm and translator can't extract args` names for now.

### CODE REVIEW

**Comment by vovapolu** [comment]
I need also to add docs about C# compilation with `debug:portable` mode and cli commands that support `pdb` files.

File: cli/src/main/scala/pravda/cli/PravdaArgsParser.scala [hunk 1]
```diff
@@ -151,6 +151,11 @@ object PravdaArgsParser extends CommandLine[PravdaConfig] {
                 opt[Unit]("visualize").action {
                   case ((), config: PravdaConfig.Compile) =>
                     config.copy(compiler = PravdaConfig.CompileMode.DotNetVisualize)
+                },
+                opt[File]("pdb").action {
```
Comment (fomkin) [inline cli/src/main/scala/pravda/cli/PravdaArgsParser.scala]: Add description.
